### ISSUE TITLE
Full image build errors

### ISSUE THREAD

**Issue by IvanFilipov** [ArrowElectronics/I.IMX8_Thor96#2]
Hello,

I am trying to build a full image for my Thor96 board with
Kernel 5.10.52 or 5.4.47, using the scripts (yocto_build_setup_thor96.sh) from the repo - 

The problem, I am facing, is that there are a lot of missing repositories, on which the yocto build is depending on.
The "do_fetch()" step for those is causing the build to fail.
For example:
```

ERROR: qtdeclarative-native-5.15.2+gitAUTOINC+104eae5b17-r0 do_fetch: Fetcher failure: Unable to find revision 104eae5b17b0ec700391e9539ee3a4f638588194 in branch 5.15.2 even from upstream
ERROR: qtdeclarative-native-5.15.2+gitAUTOINC+104eae5b17-r0 do_fetch: Fetcher failure for URL: 'git://code.qt.io/qt/qtdeclarative.git;name=qtdeclarative;branch=5.15.2;protocol=git'. Unable to fetch URL from any source.
ERROR: Task (virtual:native:/I.IMX8_Thor96/Kernel_5_10_52/imx-yocto-bsp/sources/meta-qt5/recipes-qt/qt5/qtdeclarative_git.bb:do_fetch) failed with exit code '1'

ERROR: qtbase-native-5.15.2+gitAUTOINC+40143c189b-r0 do_fetch: Fetcher failure: Unable to find revision 40143c189b7c1bf3c2058b77d00ea5c4e3be8b28 in branch 5.15.2 even from upstream
ERROR: qtbase-native-5.15.2+gitAUTOINC+40143c189b-r0 do_fetch: Fetcher failure for URL: 'git://code.qt.io/qt/qtbase.git;name=qtbase;branch=5.15.2;protocol=git'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: /I.IMX8_Thor96/Kernel_5_10_52/imx-yocto-bsp/build-xwayland-thor96/tmp/work/x86_64-linux/qtbase-native/5.15.2+gitAUTOINC+40143c189b-r0/temp/log.do_fetch.32629
ERROR: Task (/I.IMX8_Thor96/Kernel_5_10_52/imx-yocto-bsp/sources/meta-qt5/recipes-qt/qt5/qtbase-native_git.bb:do_fetch) failed with exit code '1'
```

Those are NOT the only onces that fail, I am using them only as an example.
The host machine is running Ubuntu 18.04 as per mentioned in 
_**ei_User_Guide_IMX8M_Thor96_L5_10_Rel_4_3.pdf.**_

I have tried to change the command (inside the yocto_build_setup_thor96.sh scripts)
`bitbake imx-image-full` to `bitbake imx-image-multimedia`,
in order to skip some dependencies to Qt and ML libs, but it also fails.

Do you have any recommendations on what can be changed in order the build to pass?
Also if there is an artifactory, in which the full images are stored can you provide access to it?

Thank you in advance!

**Comment by deep1989** [comment]
Hi @IvanFilipov ,

Can you please try the following changes:

File: imx-yocto-bsp/sources/meta-qt5/recipes-qt/qt5/qt5-git.inc b/recipes-qt/qt5/qt5-git.inc

`diff --git a/recipes-qt/qt5/qt5-git.inc b/recipes-qt/qt5/qt5-git.inc
index f1d724d..882a99c 100644
--- a/recipes-qt/qt5/qt5-git.inc
+++ b/recipes-qt/qt5/qt5-git.inc
@@ -7,7 +7,7 @@ QT_MODULE_BRANCH_PARAM ?= "branch=${QT_MODULE_BRANCH}"
# each module needs to define valid SRCREV
SRC_URI = " \
-    ${QT_GIT}/${QT_MODULE}.git;name=${QT_MODULE};${QT_MODULE_BRANCH_PARAM};protocol=${QT_GIT_PROTOCOL} \
**+    ${QT_GIT}/${QT_MODULE}.git;name=${QT_MODULE};${QT_MODULE_BRANCH_PARAM};protocol=${QT_GIT_PROTOCOL};nobranch=1 \**
"
CVE_PRODUCT = "qt"`

Please recompile QT package and lt will succedd.

Thanks.
